### ISSUE TITLE
sign release tarballs?

### ISSUE THREAD

**Issue by maitra** [RobPearce/slim#2]
Fedora packaging suggests that
`Where the upstream project publishes OpenPGP signatures  of their releases, Fedora packages SHOULD verify that  signature as part of the RPM build process.`
I guess you do not publish such signatures yet, so I have been asked to ask you if would consider signing the release tarballs.

Thanks!

**Comment by RobPearce** [comment]
I've also had that suggested via one of the Devuan devs and I do intend to do so once I've got time to battle with GPG

**Comment by RobPearce** [comment]
I've uploaded a SLiM-GPG-key (Fingerprint=7062FC1D324169BF98D66982D1B4238ADD8B03FB) and signature (xxx.asc) files for all releases so far. Hopefully I've done that in a way that works for your packaging efforts.
