### ISSUE TITLE
where to get ck-connector.h

### ISSUE THREAD

**Issue by maitra** [RobPearce/slim#3]
The file Ck.h appears to need a file called ck-connector.h but I can not see where to get it from. It is not packaged in Fedora.

As  a result, I get the following error:

```
Downloads/slim-1.4.0/Ck.cpp:13:10: fatal error: ck-connector.h: No such file or directory
   13 | #include <ck-connector.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/slim.dir/build.make:163: CMakeFiles/slim.dir/Ck.cpp.o] Error 1
```

**Comment by RobPearce** [comment]
You almost certainly want to build without ConsoleKit support, for Fedora. As I understand it, Fedora is a systemd environment and does not have ConsoleKit at all. Disabling ConsoleKit should prevent the build from pulling in Ck.h
